name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-java-${{ matrix.java }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]
    name: "Build with Java ${{ matrix.java }}"
    env:
      DEFAULT_JAVA: 11

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-java-${{ matrix.java }}-sonar
        restore-keys: ${{ runner.os }}-java-${{ matrix.java }}-sonar

    - name: Build with Maven
      run: mvn --errors --batch-mode clean org.jacoco:jacoco-maven-plugin:prepare-agent install

    - name: Build example projects
      run: |
        cd src/test/resources/empty-project/
        mvn --batch-mode verify
        cd ../simple-project/
        mvn --batch-mode verify
        cd ../html-report/
        mvn --batch-mode verify
        cd ../project-with-tracing-defects
        mvn --batch-mode verify
        cd ../project-with-tracing-defects-fail-build/
        mvn --batch-mode verify || true

    - name: Sonar analysis
      if: ${{ env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: |
        mvn --errors --batch-mode \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=itsallcode \
          -Dsonar.login=$SONAR_TOKEN \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Publish Test Report for Java ${{ matrix.java }}
      uses: scacap/action-surefire-report@v1
      if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
